"""Make properties.tenant_id FK explicit ON DELETE RESTRICT.

Revision ID: 007_property_tenant_fk_restrict
Revises: 006_property_indexes
Create Date: 2026-04-20 00:00:00.000000
"""
from typing import Sequence, Union

from alembic import op


revision: str = "007_property_tenant_fk_restrict"
down_revision: Union[str, None] = "006_property_indexes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Autogenerated FK names follow `<table>_<column>_fkey` in PostgreSQL.
_FK_NAME = "properties_tenant_id_fkey"


def upgrade() -> None:
    op.drop_constraint(_FK_NAME, "properties", type_="foreignkey")
    op.create_foreign_key(
        _FK_NAME,
        "properties",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )


def downgrade() -> None:
    op.drop_constraint(_FK_NAME, "properties", type_="foreignkey")
    op.create_foreign_key(
        _FK_NAME,
        "properties",
        "tenants",
        ["tenant_id"],
        ["id"],
    )
